Yann us2 vehicles
WildCodeSchool/tours-php-2009-project3-mobilean pull request #11
Opened 2020-12-18 08:53 UTC by YannRaulet

Add sections in the home page, modifications of the layout and add new lines at the end of the lines.

2020-12-18 14:17 UTC, LucyMerlier requested changes

2020-12-18 14:17 UTC, LucyMerlier commented on templates/front/product/home.html.twig
> +        <img src="https://static.wixstatic.com/media/dafe57_4fb88e1b97ce4fbc927d3d9b5e4f7014~mv2.png/v1/fill/w_480,h_480,al_c,q_85,usm_0.66_1.00_0.01/Logo%20Mobilean.webpg" class="logo-mobilean" alt=
shouldn't the logo be in the project in the assets folder?

2020-12-18 14:17 UTC, LucyMerlier commented on templates/front/product/home.html.twig
> +                    </figure>
why is the figcaption in another figure?

2021-01-06 08:38 UTC, LucyMerlier approved these changes, later dismissed

2021-01-06 13:02 UTC, LucyMerlier approved these changes

2021-01-06 13:07 UTC, RomainClair approved these changes

2021-01-06 13:07 UTC, merged