Us0 uploadimage
WildCodeSchool/tours-php-2009-project3-mobilean pull request #28
Opened 2021-01-19 08:33 UTC by erguculu

2021-01-19 14:58 UTC, FrKev1 submitted a review, later dismissed
Ok

2021-01-20 08:21 UTC, FrKev1 submitted a review, later dismissed
OK

2021-01-20 09:14 UTC, RomainClair requested changes
You probably should not mix static and dynamic images in the same directory.
And you should put your dynamic image directory in your .gitignore
Your migration/Version files are not consistent with the dev branch ones

2021-01-20 19:29 UTC, FrKev1 approved these changes

2021-01-21 09:26 UTC, RomainClair approved these changes

2021-01-21 09:26 UTC, merged