added basic contact form
WildCodeSchool/tours-php-2009-project3-mobilean pull request #32
Opened 2021-01-20 10:06 UTC by LucyMerlier

2021-01-20 10:53 UTC, YannRaulet approved these changes, later dismissed

2021-01-21 09:29 UTC, RomainClair requested changes

2021-01-21 09:29 UTC, RomainClair commented on src/DataClass/Contact.php
> +    private ?string $telephone = null;
The telephone can be anything ?

2021-01-21 15:53 UTC, YannRaulet approved these changes

2021-01-22 09:10 UTC, RomainClair approved these changes

2021-01-22 09:10 UTC, merged