Kevin us0 database
WildCodeSchool/tours-php-2009-project3-mobilean pull request #5
Opened 2020-12-16 10:09 UTC by FrKev1

Create the entities and user mysql

2020-12-16 10:18 UTC, LucyMerlier commented on src/Entity/User.php
> +    private string $password;
password should be 255 characters, not 100

2020-12-16 10:21 UTC, LucyMerlier requested changes
password length should be 255, not 100

2020-12-16 10:31 UTC, LucyMerlier submitted a review, later dismissed

2020-12-17 14:35 UTC, RomainClair requested changes
You probably should a User entity implementing the UserInterface
You should probably avoid having too small database fields. 50 characters for names can be too small

2020-12-18 09:22 UTC, LucyMerlier approved these changes, later dismissed

2020-12-21 08:06 UTC, RomainClair reviewed
You probably shouldn't have only nullable fields in all your entities.

2021-01-06 08:34 UTC, LucyMerlier approved these changes

2021-01-06 09:43 UTC, RomainClair approved these changes

2021-01-06 09:44 UTC, merged